spring:
  application:
    name: CONFIG-DEV
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      client:
        register-with-eureka: true
        fetch-registry: true
          

